version: 2
jobs:
  build:
    working_directory: ~/temp
    docker:
      - image: circleci/clojure:lein-2.8.1
      - image: ticktok/ticktok:0.2.7
    environment:
      LEIN_ROOT: nbd
      JVM_OPTS: -Xmx3200m 
    steps:
      - checkout 
      - restore_cache: # restores saved cache if checksum hasn't changed since the last run
          key: ticktok-{{ checksum "project.clj" }}
      - run: lein deps
      - save_cache: # generate and store cache in the .m2 directory using a key template
          paths:
            - ~/.m2
          key: ticktok-{{ checksum "project.clj" }}
      - run:
         name: Testing
         command: lein midje
  deploy:
    docker:
      - image: circleci/clojure:lein-2.8.1
    steps:
      - checkout
      - run:
          name: uberjar
          command: lein uberjar
      - run:
          name: Deploy to Heroku
          command: HEROKU_API_KEY="${TICKTOK_REST_PLUGIN_HEROKU_API_KEY}" lein heroku deploy

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:      
          requires:
            - build
          context: clojure-deploy
          filters:
            branches:
              only: master













